[package]
name = "abstract-ibc-host"
version = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
description = "base API contract implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# # use library feature to disable all instantiate/execute/query exports
library = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3", "stargate"] }
cosmwasm-schema = {workspace = true}
cw-utils = { workspace = true }
cw1-whitelist = { version = "0.16.0", features = ["library"]}
cw-storage-plus = {workspace = true}
serde = {workspace = true}
schemars = {workspace = true}
cw-controllers = {workspace = true}
thiserror = {workspace = true}
cw2 = {workspace = true}
semver = {workspace = true}

abstract-sdk = {workspace = true}
abstract-os = {workspace = true}

