# Note that any updates to this files will not be applied in CI
# until this file is merged into main. This is due to oddities of the labeller Github Action.
"core":
  # Match all of core folders
  - contracts/core/**/*
"app":
  # Match all of app folders
  - contracts/modules/apps/**/*
"extension":
  # Match all of extension folders
  - contracts/modules/extensions/**/*
"service":
  # Match all of extension folders
  - contracts/modules/services/**/*
"perk":
  # Match all of extension folders
  - contracts/modules/perks/**/*
"native":
  # Match all of native folders
  - contracts/native/**/*
"breaking?":
  # Match all of native folders
  - packages/abstract-os/**/*
"sdk":
  # Match all of native folders
  - packages/abstract-sdk/**/*
"extension_base":
  # Match all of native folders
  - packages/abstract-extension/**/*
"app_base":
  # Match all of native folders
  - packages/abstract-app/**/*
"build":
  - build_release.sh
"CI":
  - .github/**/*.yml
# Add "C:docs" label to documented related files and directories. 
"docs":
  - README.md
  - contracts/**/*.md
  - contracts/**/*/*.md
  