# Note that any updates to this files will not be applied in CI
# until this file is merged into main. This is due to oddities of the labeller Github Action.
"core":
  # Match all of core folders
  - contracts/core/**/*
"native":
  # Match all of native folders
  - contracts/native/**/*
"breaking?":
  # Match all of abstract-os folders
  - packages/abstract-os/**/*
"sdk":
  # Match all of sdk folders
  - packages/abstract-sdk/**/*
"api_base":
  # Match all of api base folders
  - packages/abstract-api/**/*
"app_base":
  # Match all of app base folders
  - packages/abstract-app/**/*
"build":
  - build_release.sh
"CI":
  - .github/**/*.yml
# Add "C:docs" label to documented related files and directories. 
"docs":
  - README.md
  - contracts/**/*.md
  - contracts/**/*/*.md
"boot":
  - packages/abstract-boot/**/*
