# Note that any updates to this files will not be applied in CI
# until this file is merged into main. This is due to oddities of the labeller Github Action.
"core":
  # Match all of core folders
  - contracts/core/**/*
"add-on":
  # Match all of add-on folders
  - contracts/modules/add-ons/**/*
"api":
  # Match all of api folders
  - contracts/modules/apis/**/*
"service":
  # Match all of api folders
  - contracts/modules/services/**/*
"perk":
  # Match all of api folders
  - contracts/modules/perks/**/*
"native":
  # Match all of native folders
  - contracts/native/**/*
"breaking?":
  # Match all of native folders
  - packages/abstract-os/**/*
"sdk":
  # Match all of native folders
  - packages/abstract-sdk/**/*
"api_base":
  # Match all of native folders
  - packages/abstract-api/**/*
"add-on_base":
  # Match all of native folders
  - packages/abstract-add-on/**/*
"build":
  - build_release.sh
"CI":
  - .github/**/*.yml
# Add "C:docs" label to documented related files and directories. 
"docs":
  - README.md
  - contracts/**/*.md
  - contracts/**/*/*.md
  