[workspace]
members = [
    "packages/*",
    "contracts/native/*",
    "contracts/core/*",
    "contracts/testing",
    "contracts/token",
    "contracts/modules/add-ons/etf",
    "contracts/modules/add-ons/subscription",
    "contracts/modules/apis/tendermint-staking",
    "contracts/modules/apis/dex",
    "contracts/modules/services/vesting",
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false