coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

comment: # this is a top-level key
  layout: "reach, diff, files"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

ignore:
  - "scripts"
  - "**/examples"
  - "**/*.json"
  - "packages/abstract-boot"
  # Ignore token implementation
  - "contracts/token"
  - "packages/abstract-testing"
  - "contracts/modules/apps/subscription"
  # Ignore protobuf generated files
  - "contracts/native/module-factory/src/response.rs"
  - "contracts/native/os-factory/src/response.rs"
  # We also ignore the schema generators
  - "**/schema.rs"
