[package]
name = "terraswap-dapp"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

# Keep as is until Terraswap updates.
[dependencies]
cw2 = { version = "0.13" }
cw20 = { version = "0.13" }
cosmwasm-bignumber = "2.2"
cosmwasm-std = { version = "1.0" }
cosmwasm-storage = { version = "1.0" }
cw-storage-plus = { version = "0.13" }
cw-controllers = { version = "0.13" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = "2.2"
terraswap = "2.4.0"
thiserror = { version = "1.0.21" }
abstract-os = { version = "0.1.0", path = "../../../../packages/abstract" }
abstract-api = { version = "0.1.0", path = "../../../../packages/abstract_api", features = ["library"] }
# dapp-template = { version = "0.1.0", path = "../../template" }
protobuf = { version = "2", features = ["with-bytes"] }
cw-asset = {version = "2.0.0"}
astroport = "1.0.1"

[dev-dependencies]
cosmwasm-schema = { version = "1.0" }
cw-multi-test = { version = "0.13" }
terra-mocks = { git = "https://github.com/terra-money/cosmwasm-contracts.git", rev = "b25f4ac2d7bddaa3a18838cfe51d18e1ae855dcd", package = "terra-mocks" }
terra-multi-test = { git = "https://github.com/astroport-fi/terra-plus", rev = "b3991b9b109accf445fec086ce9792b197be6ca4", package = "terra-multi-test" }

proxy = { version = "0.1.0", path = "../../../core/proxy" }
memory = { version = "0.1.0", path = "../../../native/memory" }
cw20-base = { version = "0.13", features = ["library"] }
terraswap-factory = {path = "../../../mocks/mock_terraswap/terraswap_factory" }
terraswap-pair = {  path = "../../../mocks/mock_terraswap/terraswap_pair" }
terraswap-token = { path = "../../../mocks/mock_terraswap/terraswap_token" }
