[package]
name = "abstract-os"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Abstract contract interfaces and storage layouts"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts"




[features]
boot = ["dep:boot-core"]
# for quicker tests, cargo test --lib
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["iterator"] }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
semver = { package = "cw-semver", version = "1.0.0", git = "https://github.com/Abstract-OS/cw-semver.git", features = ["serde"] }
cw-asset = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw20-base = { workspace = true }
abstract-ica = { workspace = true }

boot-core = { version = "0.5.1", workspace = true, optional = true }

[dev-dependencies]
speculoos = { workspace = true }
