[package]
name = "abstract-os"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"
description = "Abstract contract interfaces and storage layouts"
license = "GPL-2.0-or-later"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0", features = ["iterator"] }
schemars = "0.8.1"
cw-controllers = { version = "0.13" }
cw-storage-plus = { version = "0.13" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw-asset = "2.0"
cw2 = { version = "0.13" }
cw20 = { version = "0.13" }
cw20-base = { version = "0.13", features = ["library"] }

