[package]
name = "abstract-os"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
description = "Abstract contract interfaces and storage layouts"
license = {workspace = true}
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts/tree/main/packages/abstract-os"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
boot = ["boot-core"]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["iterator"] }
cosmwasm-schema = { workspace = true }
schemars = {workspace = true}
cw-controllers = {workspace = true}
cw-storage-plus = {workspace = true}
serde = {workspace = true}
cw-asset= {workspace = true}
cw2 = {workspace = true}
cw20 = {workspace = true}
cw20-base = {workspace = true}
abstract-ica = {workspace = true}

boot-core = { workspace = true, optional = true}