[package]
name = "ans-host"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

exclude = [
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
serde = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }
abstract-os = { workspace = true }
cw-asset = { workspace = true }

[dev-dependencies]
cw20 = { workspace = true }
cosmwasm-schema = { workspace = true }
rstest = { workspace = true }
speculoos = { workspace = true }

abstract-testing = { workspace = true }
