[package]
name = "osmosis-host"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

exclude = [
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []


[dependencies]
cosmwasm-std = { version =  "1.1", features = ["stargate"]}
thiserror = {workspace = true}
# dex = {workspace = true, default-features = false ,features = ["osmosis"] }
abstract-os = { workspace = true }
abstract-ibc-host = { workspace = true}
abstract-sdk = {workspace = true}
cosmwasm-schema = { workspace = true }
abstract-macros = { workspace = true }
