[package]
name = "abstract-ibc-client"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Abstract IBC Client Contract"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts"


[lib]
crate-type = ["cdylib", "rlib"]

[features]

library = []

[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cw-controllers = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
abstract-os = { workspace = true }
abstract-sdk = { workspace = true }
abstract-macros = { workspace = true }
cw-semver = { workspace = true }


[dev-dependencies]
cosmwasm-schema = { workspace = true }
abstract-testing = { workspace = true }
speculoos = { workspace = true }
