[package]
name = "version-control"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

exclude = [
  "contract.wasm",
  "hash.txt",
]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cw-semver = { workspace = true }
abstract-sdk = { workspace = true }
abstract-os = { workspace = true }
abstract-macros = { workspace = true }


[dev-dependencies]
cosmwasm-schema = { workspace = true }
abstract-boot = { workspace = true }
boot-core = { workspace = true }
anyhow = { workspace = true }
cw-multi-test = { workspace = true }
module-factory = { workspace = true }
ans-host = { workspace = true }
os-factory = { workspace = true }
proxy = { workspace = true }
manager = { workspace = true }

speculoos = { workspace = true }
