[package]
name = "dapp-template"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.16" }
cosmwasm-storage = { version = "0.16" }
cw-storage-plus = { version = "0.9.1" }
cw2 = { version = "0.9.1" }
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
pandora-os = { version = "0.1.0", path = "../../../packages/pandora-os" }
pandora-dapp-base = { version = "0.1.0", path = "../../pandora_dapp_base", features = ["library"] }


[dev-dependencies]
cosmwasm-schema = { version = "0.16" }
cw-multi-test = { version = "0.9.1" }
terra-mocks = { git = "https://github.com/terra-money/cosmwasm-contracts.git", rev = "b25f4ac2d7bddaa3a18838cfe51d18e1ae855dcd", package = "terra-mocks" }
terra-multi-test = { git = "https://github.com/astroport-fi/terra-plus", rev = "b3991b9b109accf445fec086ce9792b197be6ca4", package = "terra-multi-test" }
terraswap = "2.4.0"
cw20-base = { version = "0.9.1", features = ["library"] }
cw20 = { version = "0.9.1" }
proxy = { version = "0.1.0", path = "../../core/proxy" }
memory = { version = "0.1.0", path = "../../native/memory" }
terraswap-factory = { version = "0.1.0", path = "../../mocks/mock_terraswap/terraswap_factory" }
terraswap-pair = { version = "0.1.0", path = "../../mocks/mock_terraswap/terraswap_pair" }
terraswap-token = { version = "0.1.0", path = "../../mocks/mock_terraswap/terraswap_token" }
rstest = "0.12.0"
claim = "0.5"
