[package]
name = "dapp-template"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0" }
cosmwasm-storage = { version = "1.0" }
cw-storage-plus = { version = "0.13" }
cw2 = { version = "0.13" }
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
abstract-sdk = { path = "../../../packages/abstract-sdk" }
pandora-dapp-base = { version = "0.1.0", path = "../../pandora_dapp_base", features = ["library"] }


[dev-dependencies]
cosmwasm-schema = { version = "1.0" }
cw-multi-test = { version = "0.13" }
cw20-base = { version = "0.13", features = ["library"] }
cw20 = { version = "0.13" }
proxy = { version = "0.1.0", path = "../../core/proxy" }
memory = { version = "0.1.0", path = "../../native/memory" }
rstest = "0.12.0"
claim = "0.5"
