[package]
name = "abstract-manager"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Abstract Manager Contract"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts"

exclude = [
  "contract.wasm",
  "hash.txt",
]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export = []


[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw-asset = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
abstract-sdk = { workspace = true }
abstract-core =  { workspace = true }
semver = { workspace = true }
cw-semver = { workspace = true }
abstract-macros = { workspace = true }

[dev-dependencies]
cw20 = { workspace = true }
abstract-boot = { workspace = true }
boot-core = { workspace = true }
anyhow = { workspace = true }
account-factory = { workspace = true }
ans-host = { workspace = true }
version-control = { workspace = true }
proxy = { workspace = true }
module-factory = { workspace = true }
rstest = { workspace = true }
speculoos = { workspace = true }
abstract-api ={ workspace = true, features = ["test-utils"]}
abstract-app ={ workspace = true, features = ["test-utils"]}
abstract-testing = { workspace = true }
abstract-macros = { workspace = true }
