[package]
name = "whale-lp-staking-proxy"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"


exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
abstract-sdk = { path = "../../../packages/abstract-sdk" }
cosmwasm-std = { version = "1.0" }
cosmwasm-bignumber = "2.2.0"
cw-storage-plus = "0.13.2"
schemars = "0.8.1"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.24" }
cw2 = "0.13.0"
cw20 = "0.13.0"


[dev-dependencies]
cosmwasm-schema = { version = "1.0" }
