[package]
name = "version-control"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

exclude = [
  "contract.wasm",
  "hash.txt",
]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-controllers = {workspace = true}
cw-storage-plus = {workspace = true}
cw2 = {workspace = true}
serde = {workspace = true}
thiserror = {workspace = true}
semver = {workspace = true}
abstract-sdk = {workspace = true}
abstract-os = {workspace = true}

[dev-dependencies]
cosmwasm-schema = { workspace = true }
