[package]
name = "version-control"
version = "0.1.0"
authors = ["Abstract"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0" }
cw-controllers = { version ="0.13" }
cw-storage-plus = "0.13"
cw2 = "0.13"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
semver = "1"
abstract-sdk = { path = "../../../packages/abstract-sdk" }
abstract-os = {path = "../../../packages/abstract-os"}

[dev-dependencies]
cosmwasm-schema = { version = "1.0" }
