[package]
name = "abstract-core"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Abstract contract interfaces and storage layouts"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts"


[features]
boot = ["dep:boot-core"]
# for quicker tests, cargo test --lib

[dependencies]
cosmwasm-std = { workspace = true, features = ["iterator"] }
cosmwasm-schema = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }
cw-utils = { workspace = true }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
cw-semver = { workspace = true, features = ["serde"] }
semver = { workspace = true, features = ["serde"] }
cw-asset = { workspace = true }
cw-address-like = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw20-base = { workspace = true }
abstract-ica = { workspace = true }
boot-core = { workspace = true, optional = true }
cw-ownable = { workspace = true }

# Allows us to use a JSON Value in the proxy execute message
serde-cw-value = {git = "https://github.com/nicolaslara/serde-cw-value.git", features = ["json_schema"], branch = "nicolas/conditional-json-schema"}

[dev-dependencies]
speculoos = { workspace = true }
rstest = { workspace = true }
anyhow = { workspace = true }
abstract-testing = { path = "../abstract-testing" }
