[package]
name = "abstract-sdk"
version = "0.14.0"
authors = { workspace = true }
edition = { workspace = true }
description = "Helpers for Abstract contracts"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts/tree/main/packages/abstract-sdk"
resolver = "2"


[features]
# for quicker tests, cargo test --lib

# Expose MockModule for testing with other APIs
test-utils = ["dep:abstract-testing", "dep:cosmwasm-schema"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["iterator", "staking"] }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cw-asset = { workspace = true }
abstract-core =  { workspace = true }
semver = { workspace = true }
abstract-macros = { workspace = true}

# test-utils feature
abstract-testing = { workspace = true, optional = true }
cosmwasm-schema = {workspace = true, optional = true}

[dev-dependencies]
speculoos = { workspace = true }
cosmwasm-schema = { workspace = true }
abstract-ica = { workspace = true }
doc-comment = "0.3.3"
# Set our own feature when running tests!
abstract-sdk = { path = ".", features = ["test-utils"] }
cw-ownable = { workspace = true }