[package]
name = "abstract-sdk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Helpers for Abstract contracts"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts/tree/main/packages/abstract-sdk"


[features]
# for quicker tests, cargo test --lib
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["iterator", "staking"] }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cw-asset = { workspace = true }
abstract-os = { workspace = true }
semver = { workspace = true }
abstract-macros = { workspace = true }

[dev-dependencies]
speculoos = { workspace = true }
cosmwasm-schema = { workspace = true }
abstract-testing = { path = "../abstract-testing", default-features = false }
