[package]
name = "abstract-sdk"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
description = "Helpers for Abstract contracts"
license = {workspace = true}
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts/tree/main/packages/abstract-sdk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["iterator", "staking"] }
cosmwasm-storage = { workspace = true, features = ["iterator"] }
cw-controllers = {workspace = true}
cw-storage-plus = {workspace = true}
cw2 = {workspace = true}
cw20 = {workspace = true}
schemars = {workspace = true}
serde = {workspace = true}
thiserror = {workspace = true}
cw-asset= {workspace = true}
serde-cw-value = "0.7.0"
abstract-os = {workspace = true}
# abstract-os = {workspace = true}
