[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "1.0.21" }
pandora-os = { path = "../packages/pandora-os"}
protobuf = { version = "2", features = ["with-bytes"] }
terra-rust-api = {version ="1.2"}
tokio = { version = "1.4", features = ["full"] }
secp256k1 = { version = "0.20.3", default-features = false }
log="0.4.14"
anyhow="1.0"
cosmwasm-std = { version = "0.16" }
serde_json = "1.0.79"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
reqwest = { version = "0.11.9"}
dotenv="0.15.0"
env_logger = "0.8.3"
base64 = "0.13.0"
terra-rust-script = {git = "https://github.com/CyberHoward/terra-rust-script"}
terraswap = "2.4.0"
cw-asset = { version = "1.0.2", features = ["legacy"] }
rust_decimal="1.12.2"
rust_decimal_macros="1.12.2"
cw20 = { version = "0.9.1"}