[package]
name = "dex"
version = "0.1.0"
authors = ["CyberHoward <cyberhoward@users.noreply.github.com>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["juno"]
library = []
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
juno = ["dep:wasmswap", "dep:cw20_junoswap", "dep:terraswap"]
terra = ["dep:terraswap"]
osmosis = ["library","dep:osmosis-std", "cosmwasm-std/stargate"]

# Keep as is until TendermintStake updates.
[dependencies]
cosmwasm-std = "1.1"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
abstract-os = { version = "0.1.0", path = "../../../../packages/abstract-os" }
abstract-sdk = { version = "0.1.0", path = "../../../../packages/abstract-sdk" }
abstract-api = { version = "0.1.0", path = "../../../../packages/abstract-api", features = ["library"] }
cw-asset = {version = "2.2.0"}

# Juno dexes
cw20_junoswap = {package = "cw20", version = "0.10.0", optional = true}
wasmswap = {git = "https://github.com/Wasmswap/wasmswap-contracts", tag = "v1.0.0-beta", features = ["library"], optional = true}
# terraswap_juno = {package = "terraswap", version = "2.8.0", optional = true}

# Terra dexes
terraswap = {version = "2.8.0", optional = true}
cw20 = "0.14.0"

# Osmosis
osmosis-std = {version = "0.12.0", optional = true}

[dev-dependencies]
cosmwasm-schema = { version = "1.0" }
