name: "Pull Request Labeler"
on:
  pull_request:
    branches:
     - main
     - dev

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"