name: Publish schemas
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5
      - "v[0-9]+.[0-9]+.[0-9]+-beta*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  publish-schemas:
    runs-on: self-hosted
    container:
      image: rust:latest
    env:
      NAMESPACE: abstract
    strategy:
      matrix:
        package: [ etf, dex, proxy ]
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Generate Cargo.lock
        run: |
          cargo schema --package ${{ matrix.package }}

      # https://github.com/docker/build-push-action/issues/42
      - name: Get tag
        uses: actions/github-script@v4
        id: get_tag
        with:
          script: |
            const tag = context.ref.substring(10) || 'vTEST'
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            core.setOutput('tag', tag)
            core.setOutput('no_v', no_v)

      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'schema'
          destination_repo: 'Abstract-OS/schemas'
          destination_folder: ${{ env.NAMESPACE }}/${{ matrix.package }}/${{steps.get_tag.outputs.no_v}}
          destination_base_branch: mainline
          destination_head_branch: ${{ env.NAMESPACE }}/${{ matrix.package }}/${{steps.get_tag.outputs.no_v}}
          user_email: '32375605+adairrr@users.noreply.github.com'
          user_name: 'adairrr'
          pull_request_reviewers: 'adairrr'
