[package]
name = "abstract-testing"
version = "0.1.0"
edition = { workspace = true }


[dependencies]
cosmwasm-std = { workspace = true, features = ["iterator"] }
schemars = {workspace = true}
cw-storage-plus = {workspace = true}
serde = {workspace = true}
derive_builder = "0.12.0"
